id: P007109
initial_creation_type: ocr
source_metadata:
  id: bdr:W20519
  title: བེའུ་བུམ་སྔོན་པོའི་འགྲེལ་པ
  author: ''
  volumes:
    6fc6de9843de436a8cc3a989f05c6b99:
      image_group_id: I1PD108827
      title: ''
      volume_number: 1
      total_pages: 492
ebook_metadata:
  title: བེའུ་བུམ་སྔོན་པོའི་འགྲེལ་པ
  author: ''
  sku: P007109
  cover: cover.jpg
  layers:
  - pagination
