id: P007109
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W20519
  title: བེའུ་བུམ་སྔོན་པོའི་འགྲེལ་པ
  author: ''
  volumes:
    c5c7de83637c490ab2714f1a80adea2b:
      image_group_id: I1PD108827
      title: Volume 1 of be'u bum sngon po'i 'grel pa
      volume_number: 1
      total_pages: 492
      base_file: v001.txt
