id: I71774E07
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T12:34:23+00:00'
last_modified: '2022-06-09T04:59:14.272351+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20519
  title: བེའུ་བུམ་སྔོན་པོའི་འགྲེལ་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D0AF:
      image_group_id: I1PD108827
      title: Volume 1 of be'u bum sngon po'i 'grel pa
      total_pages: 492
      order: 1
      base_file: D0AF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
